// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Table_Per_Type_TPT__for_Entity_Framework;

#nullable disable

namespace Table_Per_Type_TPT__for_Entity_Framework.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20240223095244_createdb")]
    partial class createdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Table_Per_Type_TPT__for_Entity_Framework.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Table_Per_Type_TPT__for_Entity_Framework.Student", b =>
                {
                    b.HasBaseType("Table_Per_Type_TPT__for_Entity_Framework.ApplicationUser");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("StudentUsers", (string)null);
                });

            modelBuilder.Entity("Table_Per_Type_TPT__for_Entity_Framework.Teacher", b =>
                {
                    b.HasBaseType("Table_Per_Type_TPT__for_Entity_Framework.ApplicationUser");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TeacherUsers", (string)null);
                });

            modelBuilder.Entity("Table_Per_Type_TPT__for_Entity_Framework.Student", b =>
                {
                    b.HasOne("Table_Per_Type_TPT__for_Entity_Framework.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Table_Per_Type_TPT__for_Entity_Framework.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Table_Per_Type_TPT__for_Entity_Framework.Teacher", b =>
                {
                    b.HasOne("Table_Per_Type_TPT__for_Entity_Framework.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Table_Per_Type_TPT__for_Entity_Framework.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
